# Auto-Generated by cargo-bitbake 0.3.16
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get hello-rs could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/hello-rs/0.1.0"
SRC_URI += " file://src/"
SRC_URI += " file://LICENSE-2.0.txt"
SRC_URI += " file://Cargo.lock"
SRC_URI += " file://Cargo.toml"
SRCREV = ""
S = "${WORKDIR}"
CARGO_SRC_DIR = ""


# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
"



LIC_FILES_CHKSUM = " \
    file://LICENSE-2.0.txt;md5=3b83ef96387f14655fc854ddc3c6bd57 \
"

SUMMARY = "Hello World application"
HOMEPAGE = "https://github.com/barthelemystephane/hello_rs.git"
LICENSE = "Apache-2.0"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include hello-rs-${PV}.inc
include hello-rs.inc
